name: "Pull Request another repository"

description: "Used for pull request on another repository"

inputs:
  destination_repo:
    description: "The branch to create to push the changes. Cannot be master or main"
    required: true
  destination_head_branch:
    description: "The branch to create to push the changes. Cannot be master or main"
    required: true
  destination_base_branch:
    description: "The branch into which you want your code merged."
    required: true
    default: "main"
  pull_request_reviewers:
    description: "Pull request reviewers users"
    required: false

runs:
  using: "composite"
  steps:
    - name: Generate PR on another repo
      run: |
        if [ inputs.destination_head_branch == "main" ] || [ inputs.destination_head_branch == "master"]
        then
          echo "Destination head branch cannot be 'main' nor 'master'"
          return -1
        fi
        if [ -z "${{ inputs.pull_request_reviewers }}" ]
        then
          PULL_REQUEST_REVIEWERS=${{ inputs.pull_request_reviewers }}
        else
          PULL_REQUEST_REVIEWERS='-r '${{ inputs.pull_request_reviewers }}
        fi
        CLONE_DIR=$(mktemp -d)
        echo "Setting git variables"
        export GITHUB_TOKEN=$API_TOKEN_GITHUB
        echo "Cloning destination git repository"
        git clone "https://$API_TOKEN_GITHUB@github.com/${{ inputs.destination_repo }}.git" "$CLONE_DIR"
        cd "$CLONE_DIR"
        git checkout -b "${{ inputs.destination_head_branch }}"
        echo "Adding git commit"
        git add .
        if git status | grep -q "Changes to be committed"
        then
          git commit --message "Update from https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA"
          echo "Pushing git commit"
          git push -u origin HEAD:${{ inputs.destination_head_branch }}
          echo "Creating a pull request"
          gh pr create -t ${{ inputs.destination_head_branch }} \
                       -b ${{ inputs.destination_head_branch }} \
                       -B ${{ inputs.destination_base_branch }} \
                       -H ${{ inputs.destination_head_branch }} \
                          ${{ inputs.pull_request_reviewers }}
        else
          echo "No changes detected"
        fi
      shell: bash

branding:
  icon: "git-commit"
  color: "green"
